### ISSUE TITLE
sound when mail arrives

### ISSUE THREAD

**Issue by adonno** [adonno/Home-AssistantConfig#15]
add a sound to the home loudspeaker notification system with a sound of a mailbox when now mail arrives

**Comment by CCOSTAN** [comment]
How do you determine that new mail has arrived? open/close sensor on the mailbox?

**Comment by adonno** [comment]
Arriving Mail is determined by open-close sensor on the Lid. 
I had initial issues to get it working and had to elongate the reed sensor in order to have the sensor inside the mailbox and the brains/antenna outside under the mailbox

**Comment by adonno** [comment]
will steer away from adding audio for now since not required
