### ISSUE TITLE
Get NUT UPS Working

### ISSUE THREAD

**Issue by adonno** [adonno/Home-AssistantConfig#19]
I have a UPS that's connected to My Synology Nas via USB
I've tried to get the Integration up and Running but no dice

**Comment by adonno** [comment]
added Nut UPS via the ui 
quick and easy 

![image](https://user-images.githubusercontent.com/13216947/85956105-b5ca2680-b983-11ea-8344-0ba66c6a0468.png)

**Comment by jcallaghan** [comment]
You should unplug your UPS power source and see how the values stack up. Then open your eyes to the world of fun you could have with automations when those values get triggered.
