### ISSUE TITLE
how do you get sensor.phone

### ISSUE THREAD

**Issue by Tosko4** [adonno/Home-AssistantConfig#2]
https://github.com/adonno/Home-AssistantConfig/blob/master/automations/phone_status_notification.yaml

I would like to accomplish the same. But I don't have a sensor.phone which goes to Idle, Dialing, ringing etc. I have an iOS device too, and use the latest iOS app version.

I figured out a sensor.activity, but it shows "walking, standby, unknown" states. Tried calling, but it wont change the state to dialing or ringing.

Very curious on how you did this :)

**Comment by adonno** [comment]
The sensor.phone is related to my landline fritz.box, not mobile phone

**Comment by Tosko4** [comment]
Ah, that makes sense. Thanks @adonno
